feat(): adapt to 12.10 core
3Hren/cocaine-framework-native pull request #16
Opened 2016-09-23 14:55 UTC by antmat

2016-09-27 10:49 UTC, 3Hren requested changes

2016-09-27 10:49 UTC, 3Hren commented on include/cocaine/framework/message.hpp
> +    boost::optional<const hpack::header_t&>
Correct, but breaks the API. Need to check whether there will be no cry.

2016-09-27 10:49 UTC, 3Hren commented on src/worker/session.cpp
> +                    hpack::header::binary_unpack<uint64_t>(message.get_header<hpack::headers::trace_id<>>()->value()),
Update the code, please.

2016-09-27 10:49 UTC, 3Hren commented on src/worker/session.cpp
> +            CF_DBG("could not decode tracing headers - %s", e.what());
WTF?

2016-09-28 12:06 UTC, antmat commented on include/cocaine/framework/message.hpp
> +    boost::optional<const hpack::header_t&>
Looks like minor API breakage - in most cases only rebuild will be requiered. Besides headers are not widely used now, so I believe it will be ok.

2016-09-28 12:07 UTC, antmat commented on src/worker/session.cpp
> +                    hpack::header::binary_unpack<uint64_t>(message.get_header<hpack::headers::trace_id<>>()->value()),
what do you mean?

2016-09-28 12:09 UTC, antmat commented on src/worker/session.cpp
> +            CF_DBG("could not decode tracing headers - %s", e.what());
Ooops. I've checked if exception is thrown on incorrect data and removed to delete.

2016-09-28 12:09 UTC, antmat commented on src/worker/session.cpp
> +            CF_DBG("could not decode tracing headers - %s", e.what());
BTW, I think we need to restore CF_DBG functionality

2016-09-28 12:11 UTC, antmat commented on src/worker/session.cpp
> +            CF_DBG("could not decode tracing headers - %s", e.what());
On the first look simple 'printf' would be fine. Much simpler than using BH, ok for trivial debug.

2016-09-28 13:14 UTC, 3Hren commented on src/worker/session.cpp
> +                    hpack::header::binary_unpack<uint64_t>(message.get_header<hpack::headers::trace_id<>>()->value()),
There is no `binary_pack`, right?

2016-09-28 13:14 UTC, 3Hren commented on src/worker/session.cpp
> +            CF_DBG("could not decode tracing headers - %s", e.what());
Maybe, but not right now.

2016-09-28 13:14 UTC, antmat commented on src/worker/session.cpp
> +                    hpack::header::binary_unpack<uint64_t>(message.get_header<hpack::headers::trace_id<>>()->value()),
yep, really.

2016-09-28 13:38 UTC, 3Hren commented on include/cocaine/framework/message.hpp
> +    boost::optional<const hpack::header_t&>
I don't want to break API here, sorry.

2016-09-28 13:39 UTC, antmat commented on include/cocaine/framework/message.hpp
> +    boost::optional<const hpack::header_t&>
Ok, as you say. There will be excess copy though.

2016-09-28 15:24 UTC, 3Hren approved these changes

2016-09-28 15:25 UTC, merged