Tokens management for workers
3Hren/cocaine-framework-native pull request #20
Opened 2017-05-04 18:24 UTC by karitra

subj.

**Don't merge, ongoing tests in progress, for early review.** 

TODO:
 - [ ] some test samples

2017-05-04 18:47 UTC, 3Hren requested changes

2017-05-04 18:47 UTC, 3Hren commented on include/cocaine/framework/worker/options.hpp
> +    std::string token_type;
Unfortunately it breaks ABI. Use `other` member with public accessors instead.

2017-05-05 15:02 UTC, 3Hren requested changes

2017-05-05 15:02 UTC, 3Hren commented on include/cocaine/framework/worker/options.hpp
> +    constexpr auto TVM_TOKEN_TYPE = "TVM";
Move in `src`.

2017-05-10 17:30 UTC, karitra commented
Seems to work while using storage service as ticket provider mock, but don't yet have a clue how to make test cases more realistic, any advice? 

Also not sure that _async_ service call for `refresh_ticket` at ` tvm_service_impl_t::refresh_ticket_async` either correctly implemented or idiomatic. 

@3Hren, @antmat, PTAL.

2017-05-11 10:37 UTC, 3Hren requested changes
LGTM except those minor issues I've mentioned.

2017-05-11 10:37 UTC, 3Hren commented on src/worker/options.cpp
> +    constexpr auto DEFAULT_TOKEN_BODY = "very_secret";
Leave it empty.

2017-05-11 10:37 UTC, 3Hren commented on include/cocaine/framework/worker/options.hpp
> +    at(const std::string& name) const;
Closer, but not what I wanted.

Look, we have predefined number of options passed from cocaine-runtime. Therefore we can describe them explicitly:

```c++
std::string token_type() const;
std::string token_body() const;
```

2017-05-11 14:43 UTC, 3Hren approved these changes

2017-05-11 14:43 UTC, 3Hren commented
LGTM, @antmat TAL.

2017-05-16 14:15 UTC, merged